volumes:
  mysqlTestData:

services:
  database_test:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: character_sheet_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - mysqlTestData:/var/lib/mysql

  backend_test:
    build: ./character-sheet-back-end
    depends_on:
      - database_test
    environment:
      NODE_ENV: test
      DB_HOST: database_test
      DB_NAME: character_sheet_test
      DB_USER: test_user
      DB_PASSWORD: test_password
      JWT_SECRET: testsecret
    command: sh -c "sleep 10 && npm run test:integration"
